// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpgkoknjzbpozufpybra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZ2tva25qemJwb3p1ZnB5YnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjQ0MzcsImV4cCI6MjA2MjYwMDQzN30.QAmi2FSyuFN6hT-VD8IBRi67jsQ0BKBafweyfajNMhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);